language: python

python:
    - "2.6"
    - "2.7"

branches:
  only:
    - master

before_script:
    - python setup.py install

script:
    - python -c "from libshorttext.analyzer import *; from libshorttext.classifier import *; from libshorttext.converter import *"