language: python
python:
    - "2.6"
    - "2.7"

install:
    - pip install -q -e . --use-mirrors
    - python setup.py install
script:
    - python -c "from libshorttext.analyzer import *; from libshorttext.classifier import *; from libshorttext.converter import *"